---
defaultRules: {}
packageRules:
- package: "com.github.mxenabled.coppuccino:com.github.mxenabled.coppuccino.gradle.plugin"
  rules: {}
  suppressUntil: "2026-02-09"
- package: "com.github.mxenabled.vogue:com.github.mxenabled.vogue.gradle.plugin"
  rules: {}
  suppressUntil: "2026-02-09"
